version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic.OdeBsmJson:1:1,topic.FilteredOdeBsmJson:1:1,topic.OdeTimJson:1:1,topic.FilteredOdeTimJson:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  ppm:
    build:
      context: .
      dockerfile: Dockerfile.standalone
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - kafka
    links:
      - kafka
    volumes:
      - ${DOCKER_SHARED_VOLUME}:/ppm_data
    environment:
      REDACTION_PROPERTIES_PATH: ${REDACTION_PROPERTIES_PATH}
      RPM_DEBUG: ${RPM_DEBUG}
