version: '2'
services:
  ppmbsm:
    build:
      context: .
      dockerfile: Dockerfile.cdot
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      KAFKA_TYPE: ${KAFKA_TYPE}
      CONFLUENT_KEY: ${CONFLUENT_KEY}
      CONFLUENT_SECRET: ${CONFLUENT_SECRET}
      PPM_CONFIG_FILE: cdot_ppmBsm.properties
  ppmtim:
    build:
      context: .
      dockerfile: Dockerfile.cdot
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      KAFKA_TYPE: ${KAFKA_TYPE}
      CONFLUENT_KEY: ${CONFLUENT_KEY}
      CONFLUENT_SECRET: ${CONFLUENT_SECRET}
      PPM_CONFIG_FILE: cdot_ppmTim.properties