version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic.OdeBsmJson:1:1,topic.FilteredOdeBsmJson:1:1,topic.OdeTimJson:1:1,topic.FilteredOdeTimJson:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ppm_bsm:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      PPM_CONFIG_FILE: ppmBsm.properties
      REDACTION_PROPERTIES_PATH: ${REDACTION_PROPERTIES_PATH}
      PPM_LOG_TO_FILE: ${PPM_LOG_TO_FILE}
      PPM_LOG_TO_CONSOLE: ${PPM_LOG_TO_CONSOLE}
      RPM_DEBUG: ${RPM_DEBUG}
    depends_on:
      - kafka
    volumes:
      - ${DOCKER_SHARED_VOLUME}:/ppm_data
        
  ppm_tim:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      PPM_CONFIG_FILE: ppmTim.properties
      REDACTION_PROPERTIES_PATH: ${REDACTION_PROPERTIES_PATH}
      PPM_LOG_TO_FILE: ${PPM_LOG_TO_FILE}
      PPM_LOG_TO_CONSOLE: ${PPM_LOG_TO_CONSOLE}
      RPM_DEBUG: ${RPM_DEBUG}
    depends_on:
      - kafka
    volumes:
    - ${DOCKER_SHARED_VOLUME}:/ppm_data